### ISSUE TITLE
Potential license conflict

### ISSUE THREAD

**Issue by nikhita** [rubiojr/go-vhd#3]
I am one of the Kubernetes maintainers and we use this repo in https://github.com/kubernetes/kubernetes.

We received an issue recently (https://github.com/kubernetes/kubernetes/issues/92704) that ran a license scan on our repo and found that [a part of the code that go-vhd uses](https://github.com/rubiojr/go-vhd/blob/0bfd3b39853cdde5762efda92289f14b0ac0491b/vhd/util.go#L59-L73) is licensed under CC-BY-SA. As per the CC-BY-SA license:

> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.

This means that go-vhd would need to be licensed under CC-BY-SA, and by consequence kubernetes would need to be too.

@rubiojr would it be possible for you to update the problematic part of the code to not use code from StackOverflow? We tried removing the dependency to this repo entirely in kubernetes but that isn't an easy solution (https://github.com/kubernetes/kubernetes/pull/92749#issuecomment-653413890).

The original issue https://github.com/kubernetes/kubernetes/issues/92704 contains more details.

cc @dims @andrewsykim @andyzhangx @lachie83

**Comment by rubiojr** [comment]
@nikhita it may take me two or three days because I'm AFK but yes, happy to help.

**Comment by nikhita** [comment]
@rubiojr That's totally fine and thank you so much for the response! :)

**Comment by rubiojr** [comment]
@nikhita I've got a fix for this in https://github.com/rubiojr/go-vhd/pull/4.

I'd like to thank @vmg for the suggestions and help with the legalese.

**Comment by nikhita** [comment]
@rubiojr Thanks for the quick fix! :)

I ran into a go mod hiccup while using the latest master, created https://github.com/rubiojr/go-vhd/pull/5 to fix it. PTAL.
